project:
  type: book
  output-dir: _book

execute:
  freeze: auto

book:
  title: "Feldkurs Schweiz"
  subtitle: "Perspektiven auf Sommertrockenheit"
  author: "Olivia Romppainen-Martius, Adrien Mestrot, Benjamin Stocker"
  date: "2026/03/31"
  page-navigation: true
  chapters:
    - index.qmd
    - design.qmd
    - plan.qmd
    - links.qmd
    - references.qmd
  favicon: "figures/favicon.ico"
  twitter-card: true
  search: true
  repo-url: https://github.com/geco-bern/feldkurs_trockenheit/
  sharing: [twitter, facebook]
  navbar:
    title: " "
    logo: "images/logo_unibern_squid3.png"
    background: "#3A3A3A"
    search: true
    right:
      - text: "Home"
        file: index.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, theme-light.scss]
      dark: [cosmo, theme-dark.scss]
