# Kursplan

## Vorbereitungsphase

### Nachmittagssession 1 (20.04.2026)

* Kursorganisation, Programm und Lernziele
* Einführung in Sommertrockenheit in der Schweiz und Dürremonitoring
* Identifikation relevanter Schlüsselvariablen
* Einstieg in Datenzugang, -analyse und -interpretation; Einordnung des aktuellen Zustands in einen mehrjährigen Referenzzeitraum
* Vorgehen zur Erhebung von Stakeholder-Perspektiven und Vorbereitung der Exkursionsbesuche

### Nachmittagssession 2 (11.05.2026)

* Unterstützung beim Datenzugang, bei der Analyse und Interpretation
* Konsolidierung der Fragen an Stakeholder zu einem gemeinsamen Fragenkatalog
* Vorbereitung und Anleitung für Präsentationen (Struktur und Aufbau)
* Räumlichkeit: H4, Raum 304

## Feldphase

| Datum     | Tag | Morgen                                                        | Mittag                    | Nachmittag                                     |
|-----------|-----|---------------------------------------------------------------|---------------------------|------------------------------------------------|
| 8.6.      | Mo  | **Präsentationen und Diskussion**<br>Wetterausblick<br>09:15 GIUB 001 | Mittagessen in  der Mensa | **Rundgang Stadtklima**<br>Kontakt: C. Gwerder & S. Mannes (Stadtgrün Bern)    |
| 9.6.      | Di  | **Swisstopo**<br>Kontakt: Dr. David Oesch<br>Treffpunkt 8:50, [Seftigenstrasse 264, Bern](https://maps.app.goo.gl/EgW2YDU1h4EkCxvL8)<br>Eigenen Laptop mitbringen | Mittagessen individuell   | **Bundesamt für Umwelt**<br>Kontakt: Dr. Fabia Hüsler und Dr. Yannick Barton<br>[Mühlestrasse 2, Ittingen](https://maps.app.goo.gl/pKDwvJZKDqnXHK7g6)|
| 10.6.     | Mi  | **WSL**<br>Reise nach Zürich mit IC1 um 08:31 Uhr Bhf Bern (reservierter Wagen) | Picknick mitbringen       | **Agroscope**<br>Rückkehr individuell. Z.B. von Zürich, Reckenholz um 16:28 Uhr                    |
| 11.6.     | Do  | **Kanton Freiburg**<br>Kontakt: Jean-Claude Raemy<br>Reise nach Freiburg mit IR15 um 09:04 Uhr Bhf Bern (reservierter Wagen)<br>Danach Zug 11:32 nach Payerne| Picknick mitbringen | **MeteoSchweiz**<br>Payerne<br>Rückkehr individuell                           |
| 12.6.     | Fr  | **Trockenheit Experiment**<br>Kontakt: Madhav Thakur, Biology, Uni Bern<br>Treffpunkt: 09:00 Uhr, danach zu Fuss vom GIUB zur Forschungsstation im Bremgartenwald<br>Nach Führung gemeinsam zu Fuss zum Forstbetrieb Burgergemeinde | Picknick mitbringen | **Forstwirtschaft Burgergemeinde Bern**<br>Kontakt: Philipp Egloff                            |
| 13.6.     | Sa  | Kein Programm                                                 | Kein Programm             | Kein Programm                                  |
| 14.6.     | So  | Kein Programm                                                 | Kein Programm             | Reise ins Wallis mit IC6 um 16:07 Uhr Bhf Bern (reservierter Wagen) |
| 15.6.     | Mo  | **Integrales Wasserressourcenmanagement**<br>Abfahrt Leuk: 7.29 (R91)<br>Wasserversorgung Naters, Kontakt: Diego Wellig, Vize-Gemeindepräsident von Naters<br>Abfahrt Naters: 9:20, Ankunft Belalp: 9:59<br>Tourismus, Bewässerung, Kontakt: Mario Gertschen, CEO der Belalp Bahnen<br>Wanderung Belalp-Hohbiel Talstation<br>Wanderung zurück nach Belalp über das Tyndall-Denkmal und Altschbord |Picknick mitbringen        | **Integrales Wasserressourcenmanagement**<br>Abfahrt Belalp: 16:15<br>Ankunft Leuk: 18:28<br>Gemeinsames Nachtessen in Leuk (Pizza bestellen) mit Inputs von Daniel Volken (**Weinbau**) |
| 16.6.     | Di  | **Trockenheit Experiment**<br>[VPDrought](https://www.wsl.ch/en/projects/vpdrought/)<br>Pfynwald, WSL                        |Picknick mitbringen        | **Waldbrand Leuk**<br>Rückkehr nach Bern mit R91 um 16:30 Uhr Bhf Leuk               |

## Gruppen

Gruppe 1: 

- Wallis: Fragen zu Naters Excursion, Pfynwald (VPDrought) and Agroscope Soil Lysimeters
- Mirjam Gasche, Aline Hertli, Marion Bienz, Daniel Guerra, Anna Tschanz

Gruppe 2: 

- Jan Monbaron, Dominik Häfliger, Elia Michlig, Joelle Plüss
- Nordwestschweiz: Fragen zu WSL Keyline experiment, BAFU, HOME Experiment in Hasli

Gruppe 3: 

- Gian-Luca Grünenfelder, Elias Schmid, Jan Graber, Emma Biland
- Fribourg: Fragen an den Kanton Freiburg, Swisstopo, Meteo Schweiz

Gruppe 4: 

- Tina Affolter, Mirjam Ackermann, Alina Joos, Laurent Voser, Anouk Sommer
- Bern: Fragen an die Burgergemeinde (Forestry), Stadtgrün Bern, WSL Forest Fires (Leuk 2003)
